// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function GetTables(arg1:string):Promise<Array<models.TableInfo>>;

export function Startup(arg1:context.Context):Promise<void>;
