// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTables(arg1) {
  return window['go']['controllers']['SchemaController']['GetTables'](arg1);
}

export function Startup(arg1) {
  return window['go']['controllers']['SchemaController']['Startup'](arg1);
}
